#Projeto Prático GCP - CI - Go!

steps:

- id: "Rodando Docker Compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

- id: "Rodando o docker ps"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

- id: 'Rodando o composer'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'composer', 'install']


- id: 'Copiando .env'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

- id: 'Gerando key'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', 'artisan', 'key:generate']

- id: 'Rodando migrations'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', 'artisan', 'migrate']

- id: 'Rodando testing'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']

