version: "3"

services:

    app:
        build: .docker/app/cloudbuild
        container_name: microservicos-video-app
        environment:
            - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
            - GOOGLE_CLOUD_KEY_FILE=${GOOGLE_CLOUD_KEY_FILE}
            - GOOGLE_CLOUD_STORAGE_BUCKET=${GOOGLE_CLOUD_STORAGE_BUCKET}
            - GOOGLE_CLOUD_STORAGE_PATH_PREFIX=${GOOGLE_CLOUD_STORAGE_PATH_PREFIX}
            - GOOGLE_CLOUD_STORAGE_API_URI=${GOOGLE_CLOUD_STORAGE_API_URI}
            - TESTING_PROD=${TESTING_PROD}
        volumes:
            - .:/var/www/
        networks:
            - app-network
        depends_on:
            - db
            - redis




    nginx:
        build: .docker/nginx/cloudbuild
        container_name: microservicos-video-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app


    redis:
        image: redis:alpine
        container_name: microservicos-video-redis
        expose:
            - 6379
        networks:
            - app-network

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: microservicos-video-db
        restart: always
        tty: true
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        ports:
            - "3336:3306"
        environment:
            - MYSQL_DATABASE=microservicos_code_video
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT=root
        networks:
            - app-network



networks:
    app-network:
        driver: bridge

