<?php


namespace Tests\Feature\Http\Controllers\Api\Video;


use App\Model\Video;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Tests\Traits\TestResources;
use Tests\Traits\TestSaves;
use Tests\Traits\TestValidations;

abstract class VideoBaseControllerTestCase extends TestCase
{
    use DatabaseMigrations, TestValidations, TestSaves, TestResources;

    protected $video;
    protected $sendData;

    protected $serializedFields = [
        'id',
        'title',
        'description',
        'year_launched',
        'opened',
        'rating',
        'duration',
        'video_file',
        'thumb_file',
        'banner_file',
        'trailer_file',
        'created_at',
        'deleted_at',
        'updated_at',
        'categories',
        'genres'
    ];

    public  function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->video = factory(Video::class)->create(['opened' => false]);

        $this->sendData = [
            'title' => 'title',
            'description' => 'descriptin',
            'year_launched' => 2019,
            'rating' => Video::RATING_LIST[0],
            'duration' => 9,
        ];

    }

    protected function routeStore()
    {
        return route('videos.store');
    }

    protected function routeUpdate()
    {
        return route('videos.update', ['video' => $this->video->id]);
    }

    protected function model()
    {
        return Video::class;
    }

}
